package testdata
//This file has been generated by bindata, DO NOT EDIT!
import "github.com/apesternikov/bindata"
import "time"

var File_txt = &bindata.Bindata{ []byte{
	
0x61,0x62,0x63,},
	"file.txt", 420, time.Unix(1436111106, 0),
}