package testdata
//This file has been generated by bindata, DO NOT EDIT!
import "github.com/apesternikov/bindata"
import "time"

var File_txt = &bindata.Bindata{ Data: []byte{
	
0x61,0x62,0x63,},
	Filename: "file.txt", 
	FileMode: 420,
	Time: time.Unix(1436111106, 0),
	FullPkgPath: "/github.com/apesternikov/bindata/internal/mkbinfs/testdata/file.txt",
}