package teststatic

//This file IS NOT generated by bindata, but carefuly crafted to provide different data in the object and the file it refers
import "github.com/apesternikov/bindata"
import "time"

var File1_txt = &bindata.Bindata{Data: []byte("compiled"),
	Filename:    "file1.txt",
	FileMode:    420,
	Time:        time.Unix(1436202077, 0),
	FullPkgPath: "github.com/apesternikov/bindata/teststatic/file.txt",
}
