package teststatic
//This file has been generated by bindata, DO NOT EDIT!
import "github.com/apesternikov/bindata"
import "time"

var File_txt = &bindata.Bindata{ Data: []byte{
	
0x66,0x69,0x6c,0x65,},
	Filename: "file.txt", 
	FileMode: 420,
	Time: time.Unix(1436202078, 0),
	FullPkgPath: "github.com/apesternikov/bindata/teststatic/file.txt",
}