package dir
//This file has been generated by bindata, DO NOT EDIT!
import "github.com/apesternikov/bindata"
import "time"

var File2_txt = &bindata.Bindata{ Data: []byte{
	
0x64,0x65,0x66,},
	Filename: "file2.txt", 
	FileMode: 420,
	Time: time.Unix(1436201928, 0),
	FullPkgPath: "github.com/apesternikov/bindata/teststatic/dir/file2.txt",
}